/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BackgroundImage = { 'christmasLights' : null } |
  { 'festiveTree' : null } |
  { 'holidayDecorations' : null } |
  { 'twinklingLights' : null } |
  { 'snowyVillage' : null };
export interface DJProfile {
  'bio' : string,
  'name' : string,
  'photoUrl' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface LastUpdateResult {
  'updateTime' : Time,
  'resultText' : string,
  'updateFailed' : boolean,
}
export interface NowPlaying { 'title' : string, 'artist' : string }
export interface OnAirOverride {
  'startTime' : Time,
  'overrideProgram' : string,
  'endTime' : Time,
  'description' : string,
}
export interface Program {
  'bio' : string,
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'description' : string,
}
export interface ProgramDaySlot { 'day' : string, 'program' : Program }
export interface SongRequest {
  'songTitle' : string,
  'name' : string,
  'message' : string,
}
export interface StationInformation {
  'title' : string,
  'content' : string,
  'description' : string,
}
export type TailwindColor = { 'red' : null } |
  { 'blue' : null } |
  { 'gold' : null } |
  { 'purple' : null } |
  { 'green' : null } |
  { 'silver' : null } |
  { 'brown' : null } |
  { 'white' : null };
export interface ThemeSettings {
  'showNewsFeed' : boolean,
  'primaryColor' : TailwindColor,
  'showCountdown' : boolean,
  'accentColor' : TailwindColor,
  'backgroundImage' : BackgroundImage,
  'snowEnabled' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeatherData { 'days' : Array<WeatherDay> }
export interface WeatherDay {
  'minTemp' : number,
  'date' : string,
  'summary' : string,
  'weatherCode' : bigint,
  'maxTemp' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomProgram' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    undefined
  >,
  'addDJProfile' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearNowPlaying' : ActorMethod<[], undefined>,
  'clearOnAirOverride' : ActorMethod<[], undefined>,
  'clearSongRequests' : ActorMethod<[], undefined>,
  'deleteDJProfile' : ActorMethod<[string], undefined>,
  'deleteProgram' : ActorMethod<[string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDJProfiles' : ActorMethod<[], Array<DJProfile>>,
  'getLastUpdateResult' : ActorMethod<[], [] | [LastUpdateResult]>,
  'getNowPlaying' : ActorMethod<[], [] | [NowPlaying]>,
  'getOnAirOverride' : ActorMethod<[], [] | [OnAirOverride]>,
  'getProgramSchedule' : ActorMethod<
    [],
    Array<[string, Array<ProgramDaySlot>]>
  >,
  'getProgramsForDay' : ActorMethod<[string], Array<Program>>,
  'getSongRequests' : ActorMethod<[], Array<SongRequest>>,
  'getStationInformation' : ActorMethod<[], [] | [StationInformation]>,
  'getThemeSettings' : ActorMethod<[], ThemeSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeatherData' : ActorMethod<[], [] | [WeatherData]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'previewChanges' : ActorMethod<[], undefined>,
  'publishChanges' : ActorMethod<[], undefined>,
  'runManualUpdate' : ActorMethod<[Array<string>], LastUpdateResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOnAirOverride' : ActorMethod<[OnAirOverride], undefined>,
  'submitSongRequest' : ActorMethod<[SongRequest], undefined>,
  'updateDJProfile' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'updateNowPlaying' : ActorMethod<[string, string], undefined>,
  'updateProgram' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateStationInformation' : ActorMethod<[StationInformation], undefined>,
  'updateThemeSettings' : ActorMethod<
    [boolean, boolean, boolean, BackgroundImage, TailwindColor, TailwindColor],
    undefined
  >,
  'updateWeatherData' : ActorMethod<[WeatherData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];