/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DJProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : ExternalBlob,
});
export const Time = IDL.Int;
export const LastUpdateResult = IDL.Record({
  'updateTime' : Time,
  'resultText' : IDL.Text,
  'updateFailed' : IDL.Bool,
});
export const NowPlaying = IDL.Record({
  'title' : IDL.Text,
  'artist' : IDL.Text,
});
export const OnAirOverride = IDL.Record({
  'startTime' : Time,
  'overrideProgram' : IDL.Text,
  'endTime' : Time,
  'description' : IDL.Text,
});
export const Program = IDL.Record({
  'bio' : IDL.Text,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProgramDaySlot = IDL.Record({
  'day' : IDL.Text,
  'program' : Program,
});
export const SongRequest = IDL.Record({
  'songTitle' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
});
export const StationInformation = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'description' : IDL.Text,
});
export const TailwindColor = IDL.Variant({
  'red' : IDL.Null,
  'blue' : IDL.Null,
  'gold' : IDL.Null,
  'purple' : IDL.Null,
  'green' : IDL.Null,
  'silver' : IDL.Null,
  'brown' : IDL.Null,
  'white' : IDL.Null,
});
export const BackgroundImage = IDL.Variant({
  'christmasLights' : IDL.Null,
  'festiveTree' : IDL.Null,
  'holidayDecorations' : IDL.Null,
  'twinklingLights' : IDL.Null,
  'snowyVillage' : IDL.Null,
});
export const ThemeSettings = IDL.Record({
  'showNewsFeed' : IDL.Bool,
  'primaryColor' : TailwindColor,
  'showCountdown' : IDL.Bool,
  'accentColor' : TailwindColor,
  'backgroundImage' : BackgroundImage,
  'snowEnabled' : IDL.Bool,
});
export const WeatherDay = IDL.Record({
  'minTemp' : IDL.Float64,
  'date' : IDL.Text,
  'summary' : IDL.Text,
  'weatherCode' : IDL.Nat,
  'maxTemp' : IDL.Float64,
});
export const WeatherData = IDL.Record({ 'days' : IDL.Vec(WeatherDay) });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomProgram' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addDJProfile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearNowPlaying' : IDL.Func([], [], []),
  'clearOnAirOverride' : IDL.Func([], [], []),
  'clearSongRequests' : IDL.Func([], [], []),
  'deleteDJProfile' : IDL.Func([IDL.Text], [], []),
  'deleteProgram' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDJProfiles' : IDL.Func([], [IDL.Vec(DJProfile)], ['query']),
  'getLastUpdateResult' : IDL.Func([], [IDL.Opt(LastUpdateResult)], ['query']),
  'getNowPlaying' : IDL.Func([], [IDL.Opt(NowPlaying)], ['query']),
  'getOnAirOverride' : IDL.Func([], [IDL.Opt(OnAirOverride)], ['query']),
  'getProgramSchedule' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(ProgramDaySlot)))],
      ['query'],
    ),
  'getProgramsForDay' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
  'getSongRequests' : IDL.Func([], [IDL.Vec(SongRequest)], []),
  'getStationInformation' : IDL.Func(
      [],
      [IDL.Opt(StationInformation)],
      ['query'],
    ),
  'getThemeSettings' : IDL.Func([], [ThemeSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeatherData' : IDL.Func([], [IDL.Opt(WeatherData)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'previewChanges' : IDL.Func([], [], []),
  'publishChanges' : IDL.Func([], [], []),
  'runManualUpdate' : IDL.Func([IDL.Vec(IDL.Text)], [LastUpdateResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOnAirOverride' : IDL.Func([OnAirOverride], [], []),
  'submitSongRequest' : IDL.Func([SongRequest], [], []),
  'updateDJProfile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'updateNowPlaying' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProgram' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateStationInformation' : IDL.Func([StationInformation], [], []),
  'updateThemeSettings' : IDL.Func(
      [
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        BackgroundImage,
        TailwindColor,
        TailwindColor,
      ],
      [],
      [],
    ),
  'updateWeatherData' : IDL.Func([WeatherData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DJProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : ExternalBlob,
  });
  const Time = IDL.Int;
  const LastUpdateResult = IDL.Record({
    'updateTime' : Time,
    'resultText' : IDL.Text,
    'updateFailed' : IDL.Bool,
  });
  const NowPlaying = IDL.Record({ 'title' : IDL.Text, 'artist' : IDL.Text });
  const OnAirOverride = IDL.Record({
    'startTime' : Time,
    'overrideProgram' : IDL.Text,
    'endTime' : Time,
    'description' : IDL.Text,
  });
  const Program = IDL.Record({
    'bio' : IDL.Text,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProgramDaySlot = IDL.Record({ 'day' : IDL.Text, 'program' : Program });
  const SongRequest = IDL.Record({
    'songTitle' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
  });
  const StationInformation = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'description' : IDL.Text,
  });
  const TailwindColor = IDL.Variant({
    'red' : IDL.Null,
    'blue' : IDL.Null,
    'gold' : IDL.Null,
    'purple' : IDL.Null,
    'green' : IDL.Null,
    'silver' : IDL.Null,
    'brown' : IDL.Null,
    'white' : IDL.Null,
  });
  const BackgroundImage = IDL.Variant({
    'christmasLights' : IDL.Null,
    'festiveTree' : IDL.Null,
    'holidayDecorations' : IDL.Null,
    'twinklingLights' : IDL.Null,
    'snowyVillage' : IDL.Null,
  });
  const ThemeSettings = IDL.Record({
    'showNewsFeed' : IDL.Bool,
    'primaryColor' : TailwindColor,
    'showCountdown' : IDL.Bool,
    'accentColor' : TailwindColor,
    'backgroundImage' : BackgroundImage,
    'snowEnabled' : IDL.Bool,
  });
  const WeatherDay = IDL.Record({
    'minTemp' : IDL.Float64,
    'date' : IDL.Text,
    'summary' : IDL.Text,
    'weatherCode' : IDL.Nat,
    'maxTemp' : IDL.Float64,
  });
  const WeatherData = IDL.Record({ 'days' : IDL.Vec(WeatherDay) });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomProgram' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addDJProfile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearNowPlaying' : IDL.Func([], [], []),
    'clearOnAirOverride' : IDL.Func([], [], []),
    'clearSongRequests' : IDL.Func([], [], []),
    'deleteDJProfile' : IDL.Func([IDL.Text], [], []),
    'deleteProgram' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDJProfiles' : IDL.Func([], [IDL.Vec(DJProfile)], ['query']),
    'getLastUpdateResult' : IDL.Func(
        [],
        [IDL.Opt(LastUpdateResult)],
        ['query'],
      ),
    'getNowPlaying' : IDL.Func([], [IDL.Opt(NowPlaying)], ['query']),
    'getOnAirOverride' : IDL.Func([], [IDL.Opt(OnAirOverride)], ['query']),
    'getProgramSchedule' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(ProgramDaySlot)))],
        ['query'],
      ),
    'getProgramsForDay' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
    'getSongRequests' : IDL.Func([], [IDL.Vec(SongRequest)], []),
    'getStationInformation' : IDL.Func(
        [],
        [IDL.Opt(StationInformation)],
        ['query'],
      ),
    'getThemeSettings' : IDL.Func([], [ThemeSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeatherData' : IDL.Func([], [IDL.Opt(WeatherData)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'previewChanges' : IDL.Func([], [], []),
    'publishChanges' : IDL.Func([], [], []),
    'runManualUpdate' : IDL.Func([IDL.Vec(IDL.Text)], [LastUpdateResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOnAirOverride' : IDL.Func([OnAirOverride], [], []),
    'submitSongRequest' : IDL.Func([SongRequest], [], []),
    'updateDJProfile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'updateNowPlaying' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProgram' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateStationInformation' : IDL.Func([StationInformation], [], []),
    'updateThemeSettings' : IDL.Func(
        [
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          BackgroundImage,
          TailwindColor,
          TailwindColor,
        ],
        [],
        [],
      ),
    'updateWeatherData' : IDL.Func([WeatherData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };