/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NowPlaying {
    title: string;
    artist: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface WeatherDay {
    minTemp: number;
    date: string;
    summary: string;
    weatherCode: bigint;
    maxTemp: number;
}
export interface WeatherData {
    days: Array<WeatherDay>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ThemeSettings {
    primaryColor: TailwindColor;
    showCountdown: boolean;
    accentColor: TailwindColor;
    backgroundImage: BackgroundImage;
    snowEnabled: boolean;
}
export interface DJProfile {
    bio: string;
    name: string;
    photoUrl: ExternalBlob;
}
export interface StationInformation {
    title: string;
    content: string;
    description: string;
}
export interface Program {
    startTime: string;
    endTime: string;
    name: string;
    description: string;
}
export interface SongRequest {
    songTitle: string;
    name: string;
    message: string;
}
export interface LastUpdateResult {
    updateTime: Time;
    resultText: string;
    updateFailed: boolean;
}
export interface OnAirOverride {
    startTime: Time;
    overrideProgram: string;
    endTime: Time;
    description: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BackgroundImage {
    festiveTree = "festiveTree",
    twinklingLights = "twinklingLights",
    snowyVillage = "snowyVillage"
}
export enum TailwindColor {
    red = "red",
    blue = "blue",
    gold = "gold",
    purple = "purple",
    green = "green",
    brown = "brown",
    white = "white"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomProgram(name: string, description: string, startTime: string, endTime: string): Promise<void>;
    addDJProfile(name: string, bio: string, photo: ExternalBlob): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearNowPlaying(): Promise<void>;
    clearOnAirOverride(): Promise<void>;
    clearSongRequests(): Promise<void>;
    deleteDJProfile(name: string): Promise<void>;
    deleteProgram(name: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDJProfiles(): Promise<Array<DJProfile>>;
    getLastUpdateResult(): Promise<LastUpdateResult | null>;
    getNowPlaying(): Promise<NowPlaying | null>;
    getOnAirOverride(): Promise<OnAirOverride | null>;
    getProgramSchedule(): Promise<Array<Program>>;
    getSongRequests(): Promise<Array<SongRequest>>;
    getStationInformation(): Promise<StationInformation | null>;
    getThemeSettings(): Promise<ThemeSettings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeatherData(): Promise<WeatherData | null>;
    isCallerAdmin(): Promise<boolean>;
    previewChanges(): Promise<void>;
    publishChanges(): Promise<void>;
    runManualUpdate(files: Array<string>): Promise<LastUpdateResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setOnAirOverride(override: OnAirOverride): Promise<void>;
    submitSongRequest(songRequest: SongRequest): Promise<void>;
    updateDJProfile(name: string, bio: string, photo: ExternalBlob): Promise<void>;
    updateNowPlaying(title: string, artist: string): Promise<void>;
    updateProgram(name: string, description: string, startTime: string, endTime: string): Promise<void>;
    updateStationInformation(stationInfo: StationInformation): Promise<void>;
    updateThemeSettings(showCountdown: boolean, snowEnabled: boolean, backgroundImage: BackgroundImage, primaryColor: TailwindColor, accentColor: TailwindColor): Promise<void>;
    updateWeatherData(newWeatherData: WeatherData): Promise<void>;
}
import type { BackgroundImage as _BackgroundImage, DJProfile as _DJProfile, ExternalBlob as _ExternalBlob, LastUpdateResult as _LastUpdateResult, NowPlaying as _NowPlaying, OnAirOverride as _OnAirOverride, StationInformation as _StationInformation, TailwindColor as _TailwindColor, ThemeSettings as _ThemeSettings, UserProfile as _UserProfile, UserRole as _UserRole, WeatherData as _WeatherData, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomProgram(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomProgram(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomProgram(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addDJProfile(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDJProfile(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDJProfile(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearNowPlaying(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearNowPlaying();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearNowPlaying();
            return result;
        }
    }
    async clearOnAirOverride(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearOnAirOverride();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearOnAirOverride();
            return result;
        }
    }
    async clearSongRequests(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSongRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSongRequests();
            return result;
        }
    }
    async deleteDJProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDJProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDJProfile(arg0);
            return result;
        }
    }
    async deleteProgram(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProgram(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDJProfiles(): Promise<Array<DJProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDJProfiles();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDJProfiles();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastUpdateResult(): Promise<LastUpdateResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdateResult();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdateResult();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNowPlaying(): Promise<NowPlaying | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNowPlaying();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNowPlaying();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnAirOverride(): Promise<OnAirOverride | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnAirOverride();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnAirOverride();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgramSchedule(): Promise<Array<Program>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgramSchedule();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgramSchedule();
            return result;
        }
    }
    async getSongRequests(): Promise<Array<SongRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongRequests();
            return result;
        }
    }
    async getStationInformation(): Promise<StationInformation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStationInformation();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStationInformation();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThemeSettings(): Promise<ThemeSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getThemeSettings();
                return from_candid_ThemeSettings_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThemeSettings();
            return from_candid_ThemeSettings_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeatherData(): Promise<WeatherData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeatherData();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeatherData();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async previewChanges(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.previewChanges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.previewChanges();
            return result;
        }
    }
    async publishChanges(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishChanges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishChanges();
            return result;
        }
    }
    async runManualUpdate(arg0: Array<string>): Promise<LastUpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.runManualUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runManualUpdate(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setOnAirOverride(arg0: OnAirOverride): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOnAirOverride(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOnAirOverride(arg0);
            return result;
        }
    }
    async submitSongRequest(arg0: SongRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSongRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSongRequest(arg0);
            return result;
        }
    }
    async updateDJProfile(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDJProfile(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDJProfile(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateNowPlaying(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNowPlaying(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNowPlaying(arg0, arg1);
            return result;
        }
    }
    async updateProgram(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgram(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgram(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateStationInformation(arg0: StationInformation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStationInformation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStationInformation(arg0);
            return result;
        }
    }
    async updateThemeSettings(arg0: boolean, arg1: boolean, arg2: BackgroundImage, arg3: TailwindColor, arg4: TailwindColor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateThemeSettings(arg0, arg1, to_candid_BackgroundImage_n29(this._uploadFile, this._downloadFile, arg2), to_candid_TailwindColor_n31(this._uploadFile, this._downloadFile, arg3), to_candid_TailwindColor_n31(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateThemeSettings(arg0, arg1, to_candid_BackgroundImage_n29(this._uploadFile, this._downloadFile, arg2), to_candid_TailwindColor_n31(this._uploadFile, this._downloadFile, arg3), to_candid_TailwindColor_n31(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateWeatherData(arg0: WeatherData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeatherData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeatherData(arg0);
            return result;
        }
    }
}
function from_candid_BackgroundImage_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackgroundImage): BackgroundImage {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_DJProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DJProfile): Promise<DJProfile> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_TailwindColor_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TailwindColor): TailwindColor {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ThemeSettings_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThemeSettings): ThemeSettings {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LastUpdateResult]): LastUpdateResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NowPlaying]): NowPlaying | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OnAirOverride]): OnAirOverride | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StationInformation]): StationInformation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeatherData]): WeatherData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    name: string;
    photoUrl: _ExternalBlob;
}): Promise<{
    bio: string;
    name: string;
    photoUrl: ExternalBlob;
}> {
    return {
        bio: value.bio,
        name: value.name,
        photoUrl: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.photoUrl)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    primaryColor: _TailwindColor;
    showCountdown: boolean;
    accentColor: _TailwindColor;
    backgroundImage: _BackgroundImage;
    snowEnabled: boolean;
}): {
    primaryColor: TailwindColor;
    showCountdown: boolean;
    accentColor: TailwindColor;
    backgroundImage: BackgroundImage;
    snowEnabled: boolean;
} {
    return {
        primaryColor: from_candid_TailwindColor_n24(_uploadFile, _downloadFile, value.primaryColor),
        showCountdown: value.showCountdown,
        accentColor: from_candid_TailwindColor_n24(_uploadFile, _downloadFile, value.accentColor),
        backgroundImage: from_candid_BackgroundImage_n26(_uploadFile, _downloadFile, value.backgroundImage),
        snowEnabled: value.snowEnabled
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    blue: null;
} | {
    gold: null;
} | {
    purple: null;
} | {
    green: null;
} | {
    brown: null;
} | {
    white: null;
}): TailwindColor {
    return "red" in value ? TailwindColor.red : "blue" in value ? TailwindColor.blue : "gold" in value ? TailwindColor.gold : "purple" in value ? TailwindColor.purple : "green" in value ? TailwindColor.green : "brown" in value ? TailwindColor.brown : "white" in value ? TailwindColor.white : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    festiveTree: null;
} | {
    twinklingLights: null;
} | {
    snowyVillage: null;
}): BackgroundImage {
    return "festiveTree" in value ? BackgroundImage.festiveTree : "twinklingLights" in value ? BackgroundImage.twinklingLights : "snowyVillage" in value ? BackgroundImage.snowyVillage : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DJProfile>): Promise<Array<DJProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DJProfile_n15(_uploadFile, _downloadFile, x)));
}
function to_candid_BackgroundImage_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundImage): _BackgroundImage {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TailwindColor_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TailwindColor): _TailwindColor {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundImage): {
    festiveTree: null;
} | {
    twinklingLights: null;
} | {
    snowyVillage: null;
} {
    return value == BackgroundImage.festiveTree ? {
        festiveTree: null
    } : value == BackgroundImage.twinklingLights ? {
        twinklingLights: null
    } : value == BackgroundImage.snowyVillage ? {
        snowyVillage: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TailwindColor): {
    red: null;
} | {
    blue: null;
} | {
    gold: null;
} | {
    purple: null;
} | {
    green: null;
} | {
    brown: null;
} | {
    white: null;
} {
    return value == TailwindColor.red ? {
        red: null
    } : value == TailwindColor.blue ? {
        blue: null
    } : value == TailwindColor.gold ? {
        gold: null
    } : value == TailwindColor.purple ? {
        purple: null
    } : value == TailwindColor.green ? {
        green: null
    } : value == TailwindColor.brown ? {
        brown: null
    } : value == TailwindColor.white ? {
        white: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
